name: Auto Merge Approved PRs

on:
  schedule:
    # Runs at 4:00 AM Central Time every day
    # Central Time = UTC -4 (or -5 depending on DST)
    # Adjust cron to UTC equivalent (10 AM UTC = 4 AM CT during DST)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual run if needed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Auto-merge pull requests
        uses: ahmadnassri/action-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          # Only PRs with this label will be considered
          labels: auto-merge
          # Ensures all required checks and approvals are met
          require-status-checks: true
          require-approval: true
